apiVersion: v1
kind: Service
metadata:
  name: reverse-ip-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: reverse-ip-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
