name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t hemanthdp07/reverse-ip-app:latest .
          docker push hemanthdp07/reverse-ip-app:latest

      - name: Configure Kubeconfig for K3s
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Verify Kubernetes Connection
        run: kubectl get nodes

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install reverse-ip-app ./reverse-ip-app --namespace default --wait


      - name: Get Service Details
        run: kubectl get svc -n default
