name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t hemanthdp07/reverse-ip-app:latest .
          docker push hemanthdp07/reverse-ip-app:latest

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install reverse-ip-app ./reverse-ip-app
